version: "3.8"

services:
    nestjs-api:
        build:
            context: .
        ports:
            - 5000:5000
        environment:
            - SERVER_PORT=5000
        volumes:
            - ./:/app
